### ISSUE TITLE
I asked them to open source it so I could contribute 

### ISSUE THREAD

**Issue by 5HT2** [RIPBackdoored/Meteor-Client-0.3.2-Deobf-Source-Leak#1]
I hope they finally make their mind up. Skids going to skid, closed source won't stop it

**Comment by squidoodly** [comment]
This is what we have been waiting for. Quite a while ago we said that when someone deobfuscated the client we would go open source but no one tried. We already had a plan and if this does get finished we will be following that plan to make the official source available to the public. I look forward to seeing what you have to contribute.

**Comment by MineGame159** [comment]
;)

**Comment by BitBuf** [comment]
> I asked them to open source it so I could contribute

weird

**Comment by thaqalayn** [comment]
brapppppp

**Comment by fee1-dead** [comment]
me when my client deobfed: I have plans to make it os

**Comment by squidoodly** [comment]
I said we had plans. We’ve been asking people to actually deobfuscate the client for a long time now and said that when it did finally get cracked we could be going open source. We made a plan months ago on what we were going to do in this eventuality. But I appreciate you trying to degrade me. :)

**Comment by fee1-dead** [comment]
lol i don't develop clients and i know nothing about this client. so it wasn't an attempt to degrade you. And what exactly did you mean by getting cracked = going open source It just sounds like a back up plan to make you look good or something you can go open source without getting cracked why is it necessary?

**Comment by squidoodly** [comment]
We just used it as a metric for being a big enough client to not get stolen from without people noticing.

**Comment by 5HT2** [comment]
# :moyai:

**Comment by squidoodly** [comment]
https://github.com/MineGame159/meteor-client

**Comment by MineGame159** [comment]
pog
